[package]
name = "x86-tiny-emulator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general_registers = {path = "general_registers"}